// journal.data.js

export const journalPosts = [
    {
        id: 1,
        title: "The Art of the Perfect Pour-Over",
        category: "brewing",
        categoryLabel: "Brewing Guides",
        image: "images/journal/pour-over.jpg",
        author: "Layla Hassan",
        date: "2026-08-28",
        readTime: 6,
        featured: true,
        excerpt:
            "Water temperature, grind size, and timing all matter more than you think. Here is our house method for a clean, balanced cup.",
        content: [
            "A great pour-over starts long before the water hits the grounds. It starts with the beans themselves, and how recently they were roasted and ground. For the brightest cup, grind just before brewing and use water that has rested off the boil for about thirty seconds.",
            "We use a ratio of roughly 1 gram of coffee to 16 grams of water, adjusted slightly depending on the roast. A medium-fine grind, similar to table salt, gives an even extraction without clogging the filter.",
            "Start with a bloom: pour just enough water to saturate the grounds and let them breathe for 30 to 45 seconds. This releases trapped carbon dioxide and helps the rest of the brew extract evenly.",
            "From there, pour in slow, steady circles, keeping the water level consistent. Aim for a total brew time of 2:30 to 3:30 minutes. If your coffee tastes sour, try a finer grind or a longer brew time. If it tastes bitter, go coarser or pull the brew shorter.",
            "The best part about pour-over is that it rewards small adjustments. Keep a simple log of your ratios and times, and within a few cups you will land on the recipe that suits your beans and your palate.",
        ],
    },
    {
        id: 2,
        title: "Where Your Coffee Comes From: A Journey to Origin",
        category: "culture",
        categoryLabel: "Coffee Culture",
        image: "images/journal/origin-farm.jpg",
        author: "Marcus Bennett",
        date: "2026-08-15",
        readTime: 8,
        featured: false,
        excerpt:
            "Behind every bag of beans is a farm, a family, and a season of careful work. We visited one of our partner farms to see it firsthand.",
        content: [
            "Coffee is a fruit before it is ever a drink. On the hillsides where our beans are grown, cherries ripen unevenly across the same branch, which means much of the harvest is still done by hand, one cherry at a time.",
            "We spent a week with one of our long-term partner farms, watching the process from picking through washing, fermenting, and drying. Every stage shapes the final flavor in ways that are easy to take for granted from behind the counter.",
            "What struck us most was the patience involved. Cherries are pulped the same day they are picked, then fermented for anywhere from 12 to 48 hours depending on the desired profile, before a long, slow dry on raised beds.",
            "Paying fair, transparent prices for that work is not just an ethical stance for us, it is also how we guarantee consistent quality year after year. A well-paid farm can afford to be selective about what makes it into your cup.",
        ],
    },
    {
        id: 3,
        title: "Cold Brew vs Iced Coffee: What Is the Difference?",
        category: "brewing",
        categoryLabel: "Brewing Guides",
        image: "images/journal/cold-brew.jpg",
        author: "Layla Hassan",
        date: "2026-08-02",
        readTime: 5,
        featured: false,
        excerpt:
            "They look similar in the glass, but the brewing method changes everything about the taste. Here is how to tell them apart, and when to choose each.",
        content: [
            "Iced coffee is simply coffee brewed hot, using your normal method, then cooled and poured over ice. It keeps the brighter, more acidic notes of the roast, since hot water extracts differently than cold water.",
            "Cold brew, on the other hand, is steeped with cold or room-temperature water for 12 to 24 hours. The slower extraction pulls out fewer acidic compounds, which is why cold brew tastes smoother and naturally sweeter.",
            "Neither method is better across the board. If you love the bright, fruity notes of a light roast, iced coffee will show them off. If you prefer a mellow, low-acid glass you can sip slowly, reach for cold brew.",
            "Our baristas are always happy to walk you through both, and we keep a rotating cold brew on tap so you can taste the difference for yourself.",
        ],
    },
    {
        id: 4,
        title: "5 Coffee-Inspired Desserts to Try This Weekend",
        category: "recipes",
        categoryLabel: "Recipes",
        image: "images/journal/desserts.jpg",
        author: "Sara Youssef",
        date: "2026-07-22",
        readTime: 7,
        featured: false,
        excerpt:
            "From an easy affogato to a slow-baked tiramisu, these five recipes turn your favorite roast into dessert.",
        content: [
            "1. Affogato: Pour a hot shot of espresso directly over a scoop of good vanilla ice cream. It takes thirty seconds and tastes like a small celebration.",
            "2. Coffee Granita: Freeze sweetened, strong coffee in a shallow dish, scraping it with a fork every 30 minutes until it forms light, icy crystals.",
            "3. Mocha Pots de Crème: Fold a shot of espresso into a classic chocolate custard base for a rich, make-ahead dinner party dessert.",
            "4. Tiramisu: The classic layered dessert of espresso-soaked ladyfingers and mascarpone cream still holds up as one of the best ways to use a strong, dark roast.",
            "5. Coffee Caramel Sauce: Simmer sugar, cream, and butter with a shot of espresso for a sauce that is just as good on ice cream as it is stirred back into your next cup.",
        ],
    },
    {
        id: 5,
        title: "Why We Chose Direct Trade",
        category: "sustainability",
        categoryLabel: "Sustainability",
        image: "images/journal/direct-trade.jpg",
        author: "Marcus Bennett",
        date: "2026-07-10",
        readTime: 6,
        featured: false,
        excerpt:
            "We buy the majority of our beans directly from the farms that grow them. Here is why that matters for quality, and for the people behind every bag.",
        content: [
            "Direct trade means we build relationships with individual farms rather than buying anonymously through a broker. We visit the farms, taste multiple lots each season, and agree on a price before the harvest even begins.",
            "This gives farmers something that fluctuating commodity markets rarely offer: certainty. They can plan for the season ahead, invest in better processing equipment, and pay their workers fairly, knowing what the crop is worth.",
            "For us, it means tighter quality control and full traceability. When you see an origin on our shelf, we can tell you exactly which farm it came from and how it was processed.",
            "It costs more than buying on the open market, and we think that is the point. Good coffee should be worth what it actually takes to grow it.",
        ],
    },
    {
        id: 6,
        title: "Meet the Roaster: Behind Our House Blend",
        category: "culture",
        categoryLabel: "Coffee Culture",
        image: "images/journal/roaster.jpg",
        author: "Sara Youssef",
        date: "2026-06-29",
        readTime: 5,
        featured: false,
        excerpt:
            "Our house blend has stayed on the menu since day one. We sat down with the roaster who built it to find out why it works.",
        content: [
            "Building a house blend that tastes the same every single batch is harder than it sounds. Green coffee is an agricultural product, and every new crop arrives slightly different.",
            "Our roaster tastes each incoming lot against the last one, adjusting the blend ratio in small increments to keep the profile consistent, rather than keeping the recipe rigidly fixed.",
            "The goal for our house blend was a coffee that works equally well black, with milk, or over ice, without ever tasting flat. That balance takes a mix of washed and natural process beans from two different regions.",
            "It is a small, deliberate craft, repeated every week, so that the cup in your hand tastes like the one you had last month.",
        ],
    },
    {
        id: 7,
        title: "A Beginner's Guide to Espresso at Home",
        category: "brewing",
        categoryLabel: "Brewing Guides",
        image: "images/journal/espresso-home.jpg",
        author: "Layla Hassan",
        date: "2026-06-14",
        readTime: 9,
        featured: false,
        excerpt:
            "Getting a good shot at home is mostly about dialing in a few key variables. Here is where to start if you just got your first machine.",
        content: [
            "The three variables that matter most are dose, grind size, and shot time. A common starting point is an 18 gram dose, ground fine, extracted into roughly 36 grams of liquid over about 28 seconds.",
            "If your shot runs too fast and tastes sour or thin, grind finer. If it runs too slow and tastes bitter or harsh, grind coarser. Small adjustments make a big difference at this scale.",
            "Fresh beans matter even more for espresso than for other methods, since the concentrated brewing exaggerates any staleness. Try to use beans within two to four weeks of their roast date.",
            "Finally, do not skip the tamp. A level, firm tamp helps water flow through the puck evenly, which is one of the simplest ways to avoid a sour or uneven shot.",
        ],
    },
    {
        id: 8,
        title: "Our New Winter Menu Is Here",
        category: "news",
        categoryLabel: "News",
        image: "images/journal/winter-menu.jpg",
        author: "Coffee Shop Team",
        date: "2026-06-01",
        readTime: 3,
        featured: false,
        excerpt:
            "Warm spices, seasonal roasts, and a returning favorite: here is everything new on the menu this season.",
        content: [
            "Starting this week, our winter menu brings back the spiced maple latte, along with a new cardamom cold brew for anyone who wants something warming served over ice.",
            "We are also featuring a limited seasonal roast, a washed Ethiopian lot with notes of orange blossom and brown sugar, available as whole bean or ground.",
            "As always, every seasonal drink can be made dairy-free with oat, almond, or soy milk at no extra charge.",
            "Stop by the shop or check the app to see the full lineup, available while supplies last.",
        ],
    },
    {
        id: 9,
        title: "From Bean to Cup: How We Reduce Waste",
        category: "sustainability",
        categoryLabel: "Sustainability",
        image: "images/journal/waste-reduction.jpg",
        author: "Marcus Bennett",
        date: "2026-05-18",
        readTime: 6,
        featured: false,
        excerpt:
            "Spent grounds, packaging, and water use all add up. Here are the small changes we have made to cut down our footprint.",
        content: [
            "Used coffee grounds are one of the easiest things to keep out of the landfill. We bag ours for anyone who wants them for composting or gardening, free at the counter.",
            "Our packaging has moved to compostable bags with a resealable strip, replacing the plastic-lined bags we used previously, without sacrificing the freshness seal our beans need.",
            "In the shop, our espresso machine recirculates rinse water through a heat exchanger, cutting water use per shot by a meaningful margin compared to our old equipment.",
            "None of these changes are dramatic on their own, but together they add up to a noticeably lighter footprint per cup, and we are always looking for the next small improvement.",
        ],
    },
];
